<a href="https://colab.research.google.com/github/HIMAL98/ppml/blob/main/NUMPY1_240901127_ppml.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np
a=np.array([[1,2,4],[5,8,7]])
print("Array created:\n",a)

b=np.zeros((3,4))
print("Array with all zeros:\n",b)

c=np.full((3,3),6)
print("Array with all 6S:\n",c)

d=np.random.random((2,2))
print("Random array:\n",d)

import numpy as np
e=np.arange(0,30,5)
print(e)

arr=np.array([[1,2,3,4],[5,2,4,2],[1,2,0,1]])
newarr=arr.reshape(4,3)
print("\nOriginal array:\n",arr)
print("Reshaped array[4,3]:\n",newarr)

#flatten array
flarr=arr.flatten()
print("\nOriginal array:\n",arr)
print("\nFlattened array:\n",flarr)

import numpy as np
arr=np.array([[1,2,3,4],[5,2,4,2],[1,2,0,1]])
print("\nNo .of dimensions:\n",arr.ndim)
print("\nShape of array:\n",arr.shape)
print("\nSize of array:\n",arr.size)
print("\nArray type:\n",arr.dtype)
newtype=arr.astype('f')
print("\nConverted array element:\n",newtype)
print("\nConverted Array type:\n",newtype.dtype)

import numpy as np
p=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(p[3:0:-1])









Array created:
 [[1 2 4]
 [5 8 7]]
Array with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Array with all 6S:
 [[6 6 6]
 [6 6 6]
 [6 6 6]]
Random array:
 [[0.54105324 0.45582266]
 [0.86282917 0.6850616 ]]
[ 0  5 10 15 20 25]

Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Reshaped array[4,3]:
 [[1 2 3]
 [4 5 2]
 [4 2 1]
 [2 0 1]]

Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]

Flattened array:
 [1 2 3 4 5 2 4 2 1 2 0 1]

No .of dimensions:
 2

Shape of array:
 (3, 4)

Size of array:
 12

Array type:
 int64

Converted array element:
 [[1. 2. 3. 4.]
 [5. 2. 4. 2.]
 [1. 2. 0. 1.]]

Converted Array type:
 float32
[[10 11 12]
 [ 7  8  9]
 [ 4  5  6]]
